[valon_controller]
rf_level = 10
valon_port = "COM3"

[zaber_controller]
zaber_speed = 0.1
zaber_homing_speed = 2.0
zaber_port = "COM5"

[awg_controller]
awg_status = false
awg_freq = 30
awg_run_mode = "null"
awg_ch_1_output = false
awg_ch_2_output = false

[oscilloscope_controller]
resolution = 100000.0
sample_rate = 500000000.0
window_type = "Rectangular"
gate_position = 1.845e-05
math_averages = 1000000

[delay_generator_controller]
trigger_rate = 5.0
