[project]
name = "surf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pydantic>=2.12.5",
    "pyqtdarktheme>=2.1.0",
    "pyqtgraph>=0.14.0",
    "pip>=25.3",
    "pyserial>=3.5",
    "pyside6>=6.9.2",
    "pythonnet>=3.0.5",
    "pyvisa>=1.15.0",
    "pyvisa-py>=0.8.1",
    "qasync>=0.28.0",
    "scipy>=1.16.2",
    "tomli-w>=1.2.0",
    "zaber-motion>=7.13.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.7",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # Ruff
    "RUF",
    # flake8-builtins
    "A",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # flake8-simplify
    "SIM",
    # flake8-use-pathlib
    "PTH",
    # Numpy
    "NPY",
    # Pandas
    "PD"
]
ignore = [
    # Line Length
    "E501",
    # Combine If with Or
    "SIM114"
]
