# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValonWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def __init__(self):
        self.gridLayoutWidget = None
        self.SynthPowerLabel = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 504)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 40, 401, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        # stepsize Label
        self.StepSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.StepSizeLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StepSizeLabel.setObjectName("StepSizeLabel")
        self.gridLayout.addWidget(self.StepSizeLabel, 1, 0, 1, 1)

        # synthPowerInput
        self.SynthPowerInput = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.SynthPowerInput.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.SynthPowerInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SynthPowerInput.setObjectName("SynthPowerInput")
        self.SynthPowerInput.addItem("---")
        self.SynthPowerInput.addItem("Internal")
        self.SynthPowerInput.addItem("External")

        self.gridLayout.addWidget(self.SynthPowerInput, 4, 1, 1, 1)
        self.SynthPowerInput.activated[str].connect(self.SetSynthPower(self))   #adds an action whenever a different index is chosen
        self.gridLayout.addWidget(self.StopFrequencyInputC, 2, 2, 1, 1)
        self.SynthPowerInputC = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SynthPowerInputC.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.SynthPowerInputC.setText("")
        self.SynthPowerInputC.setObjectName("SynthPowerInputC")
        self.gridLayout.addWidget(self.SynthPowerInputC, 4, 2, 1, 1)
        self.SynthPowerLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SynthPowerLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.SynthPowerLabel.setObjectName("SynthPowerLabel")
        self.gridLayout.addWidget(self.SynthPowerLabel, 4, 0, 1, 1)
        self.SynthPowerLabel.setBuddy(self.SynthPowerInput)

        # RF Level
        self.RFLabelInputC = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RFLabelInputC.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.RFLabelInputC.setText("")
        self.RFLabelInputC.setObjectName("RFLabelInputC")
        self.gridLayout.addWidget(self.RFLabelInputC, 3, 2, 1, 1)
        self.RFLabelInput = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.RFLabelInput.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.RFLabelInput.setObjectName("RFLabelInput")
        self.gridLayout.addWidget(self.RFLabelInput, 3, 1, 1, 1)
        self.RFLevelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RFLevelLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.RFLevelLabel.setObjectName("RFLevelLabel")
        self.gridLayout.addWidget(self.RFLevelLabel, 3, 0, 1, 1)
        self.RFLevelLabel.setBuddy(self.RFLabelInput)

        #StopFrequency
        self.StopFrequencyLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.StopFrequencyLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StopFrequencyLabel.setObjectName("StopFrequencyLabel")
        self.gridLayout.addWidget(self.StopFrequencyLabel, 2, 0, 1, 1)
        self.StopFrequencyInputC = QtWidgets.QLabel(self.gridLayoutWidget)
        self.StopFrequencyInputC.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StopFrequencyInputC.setText("")
        self.StopFrequencyInputC.setObjectName("StopFrequencyInputC")
        self.StopFrequencyInput = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.StopFrequencyInput.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StopFrequencyInput.setObjectName("StopFrequencyInput")
        self.gridLayout.addWidget(self.StopFrequencyInput, 2, 1, 1, 1)
        self.StopFrequencyLabel.setBuddy(self.StopFrequencyInput)

        #StepSizeInput
        self.StepSizeInput = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.StepSizeInput.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StepSizeInput.setObjectName("StepSizeInput")
        self.gridLayout.addWidget(self.StepSizeInput, 1, 1, 1, 1)
        self.StepSizeInputC = QtWidgets.QLabel(self.gridLayoutWidget)
        self.StepSizeInputC.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.StepSizeInputC.setText("")
        self.StepSizeInputC.setObjectName("StepSizeInputC")
        self.gridLayout.addWidget(self.StepSizeInputC, 1, 2, 1, 1)
        self.StepSizeLabel.setBuddy(self.StepSizeInput)

        #ValonFrequency
        self.ValonFrequencyLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ValonFrequencyLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ValonFrequencyLabel.setObjectName("ValonFrequencyLabel")
        self.gridLayout.addWidget(self.ValonFrequencyLabel, 0, 0, 1, 1)
        self.ValonFrequencyInput = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.ValonFrequencyInput.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ValonFrequencyInput.setObjectName("ValonFrequencyInput")
        self.gridLayout.addWidget(self.ValonFrequencyInput, 0, 1, 1, 1)
        self.ValonFrequencyInputC = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ValonFrequencyInputC.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ValonFrequencyInputC.setText("")
        self.ValonFrequencyInputC.setObjectName("ValonFrequencyInputC")
        self.gridLayout.addWidget(self.ValonFrequencyInputC, 0, 2, 1, 1)
        self.ValonFrequencyLabel.setBuddy(self.ValonFrequencyInput)


        # Maybe take this out for now
        self.actionSynth_ToolBar = QtWidgets.QAction(Form)
        self.actionSynth_ToolBar.setCheckable(True)
        self.actionSynth_ToolBar.setObjectName("actionSynth_ToolBar")





        self.retranslateUi(Form)
        self.ValonFrequencyInput.valueChanged['QString'].connect(self.ValonFrequencyInputC.setText) # type: ignore
        self.StepSizeInput.valueChanged['QString'].connect(self.StepSizeInputC.setText) # type: ignore
        self.StopFrequencyInput.valueChanged['QString'].connect(self.StopFrequencyInputC.setText) # type: ignore
        self.RFLabelInput.valueChanged['QString'].connect(self.RFLabelInputC.setText) # type: ignore
        self.SynthPowerInput.currentTextChanged['QString'].connect(self.SynthPowerInputC.setText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def SetSynthPower(self, index):
         if index == 'External':
            print(index)
         elif index == 'Internal':
            print(index)
         else:
            print('Not a Valid Command')

    #def SetRFLevel(self):
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StepSizeLabel.setText(_translate("Form", "Step Size"))
        self.StopFrequencyLabel.setText(_translate("Form", "Stop Frequency"))
        self.RFLevelLabel.setText(_translate("Form", "RF Level"))
        self.SynthPowerLabel.setText(_translate("Form", "Synth Power"))
        self.ValonFrequencyLabel.setText(_translate("Form", "Valon Frequency"))
        self.ValonFrequencyInputC.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.actionSynth_ToolBar.setText(_translate("Form", "Synth ToolBar"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())