[valon_controller]
rf_output = true
rf_level = 10.0
valon_port = "COM3"
synth_power = true
ref_source = "Internal"
ref_freq = 10.00

[zaber_controller]
zaber_scanning_speed = 0.003
zaber_moving_speed = 2.0
zaber_step_size = 0.07
zaber_port = "COM5"

[awg_controller]
awg_status = true
awg_freq = 30.0
awg_run_mode = "Triggered"
awg_ch_1_output = false
awg_ch_2_output = true

[oscilloscope_controller]
channel = "CH4"
acq_rate = 300
sample_rate = 500
math_averages = 1000000
visa_address = "TCPIP0::169.254.23.223::inst0::INSTR"

[oscilloscope_controller.math3]
window = "Rectangular"
resolution = 890.0
gate_position = 0.6

[oscilloscope_controller.math4]
window = "Hanning"
resolution = 100.0
gate_position = 18.45

[delay_generator_controller]
trigger_rate = 5.0

[scope_preset]
root_path = "C:\\Documents and Settings\\Administrator\\My Documents\\Setups_for_lab"

[scope_preset.presets.cavity]
name = "Cavity"
path = "cavity000.set"

[scope_preset.presets.mol_peak]
name = "Mol Peak"
path = "cavity_ch2000002.set"
